// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/rpc/error_details.proto

// Protobuf Java Version: 3.25.2
package com.viam.shaded.com.google.rpc;

/**
 * <pre>
 * Describes violations in a client request. This error type focuses on the
 * syntactic aspects of the request.
 * </pre>
 *
 * Protobuf type {@code google.rpc.BadRequest}
 */
public  final class BadRequest extends
    com.google.protobuf.GeneratedMessageLite<
        BadRequest, BadRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:google.rpc.BadRequest)
    BadRequestOrBuilder {
  private BadRequest() {
    fieldViolations_ = emptyProtobufList();
  }
  public interface FieldViolationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.rpc.BadRequest.FieldViolation)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * A path that leads to a field in the request body. The value will be a
     * sequence of dot-separated identifiers that identify a protocol buffer
     * field.
     *
     * Consider the following:
     *
     *     message CreateContactRequest {
     *       message EmailAddress {
     *         enum Type {
     *           TYPE_UNSPECIFIED = 0;
     *           HOME = 1;
     *           WORK = 2;
     *         }
     *
     *         optional string email = 1;
     *         repeated EmailType type = 2;
     *       }
     *
     *       string full_name = 1;
     *       repeated EmailAddress email_addresses = 2;
     *     }
     *
     * In this example, in proto `field` could take one of the following values:
     *
     * * `full_name` for a violation in the `full_name` value
     * * `email_addresses[1].email` for a violation in the `email` field of the
     *   first `email_addresses` message
     * * `email_addresses[3].type[2]` for a violation in the second `type`
     *   value in the third `email_addresses` message.
     *
     * In JSON, the same values are represented as:
     *
     * * `fullName` for a violation in the `fullName` value
     * * `emailAddresses[1].email` for a violation in the `email` field of the
     *   first `emailAddresses` message
     * * `emailAddresses[3].type[2]` for a violation in the second `type`
     *   value in the third `emailAddresses` message.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @return The field.
     */
    java.lang.String getField();
    /**
     * <pre>
     * A path that leads to a field in the request body. The value will be a
     * sequence of dot-separated identifiers that identify a protocol buffer
     * field.
     *
     * Consider the following:
     *
     *     message CreateContactRequest {
     *       message EmailAddress {
     *         enum Type {
     *           TYPE_UNSPECIFIED = 0;
     *           HOME = 1;
     *           WORK = 2;
     *         }
     *
     *         optional string email = 1;
     *         repeated EmailType type = 2;
     *       }
     *
     *       string full_name = 1;
     *       repeated EmailAddress email_addresses = 2;
     *     }
     *
     * In this example, in proto `field` could take one of the following values:
     *
     * * `full_name` for a violation in the `full_name` value
     * * `email_addresses[1].email` for a violation in the `email` field of the
     *   first `email_addresses` message
     * * `email_addresses[3].type[2]` for a violation in the second `type`
     *   value in the third `email_addresses` message.
     *
     * In JSON, the same values are represented as:
     *
     * * `fullName` for a violation in the `fullName` value
     * * `emailAddresses[1].email` for a violation in the `email` field of the
     *   first `emailAddresses` message
     * * `emailAddresses[3].type[2]` for a violation in the second `type`
     *   value in the third `emailAddresses` message.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @return The bytes for field.
     */
    com.google.protobuf.ByteString
        getFieldBytes();

    /**
     * <pre>
     * A description of why the request element is bad.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <pre>
     * A description of why the request element is bad.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * <pre>
   * A message type used to describe a single bad request field.
   * </pre>
   *
   * Protobuf type {@code google.rpc.BadRequest.FieldViolation}
   */
  public  static final class FieldViolation extends
      com.google.protobuf.GeneratedMessageLite<
          FieldViolation, FieldViolation.Builder> implements
      // @@protoc_insertion_point(message_implements:google.rpc.BadRequest.FieldViolation)
      FieldViolationOrBuilder {
    private FieldViolation() {
      field_ = "";
      description_ = "";
    }
    public static final int FIELD_FIELD_NUMBER = 1;
    private java.lang.String field_;
    /**
     * <pre>
     * A path that leads to a field in the request body. The value will be a
     * sequence of dot-separated identifiers that identify a protocol buffer
     * field.
     *
     * Consider the following:
     *
     *     message CreateContactRequest {
     *       message EmailAddress {
     *         enum Type {
     *           TYPE_UNSPECIFIED = 0;
     *           HOME = 1;
     *           WORK = 2;
     *         }
     *
     *         optional string email = 1;
     *         repeated EmailType type = 2;
     *       }
     *
     *       string full_name = 1;
     *       repeated EmailAddress email_addresses = 2;
     *     }
     *
     * In this example, in proto `field` could take one of the following values:
     *
     * * `full_name` for a violation in the `full_name` value
     * * `email_addresses[1].email` for a violation in the `email` field of the
     *   first `email_addresses` message
     * * `email_addresses[3].type[2]` for a violation in the second `type`
     *   value in the third `email_addresses` message.
     *
     * In JSON, the same values are represented as:
     *
     * * `fullName` for a violation in the `fullName` value
     * * `emailAddresses[1].email` for a violation in the `email` field of the
     *   first `emailAddresses` message
     * * `emailAddresses[3].type[2]` for a violation in the second `type`
     *   value in the third `emailAddresses` message.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @return The field.
     */
    @java.lang.Override
    public java.lang.String getField() {
      return field_;
    }
    /**
     * <pre>
     * A path that leads to a field in the request body. The value will be a
     * sequence of dot-separated identifiers that identify a protocol buffer
     * field.
     *
     * Consider the following:
     *
     *     message CreateContactRequest {
     *       message EmailAddress {
     *         enum Type {
     *           TYPE_UNSPECIFIED = 0;
     *           HOME = 1;
     *           WORK = 2;
     *         }
     *
     *         optional string email = 1;
     *         repeated EmailType type = 2;
     *       }
     *
     *       string full_name = 1;
     *       repeated EmailAddress email_addresses = 2;
     *     }
     *
     * In this example, in proto `field` could take one of the following values:
     *
     * * `full_name` for a violation in the `full_name` value
     * * `email_addresses[1].email` for a violation in the `email` field of the
     *   first `email_addresses` message
     * * `email_addresses[3].type[2]` for a violation in the second `type`
     *   value in the third `email_addresses` message.
     *
     * In JSON, the same values are represented as:
     *
     * * `fullName` for a violation in the `fullName` value
     * * `emailAddresses[1].email` for a violation in the `email` field of the
     *   first `emailAddresses` message
     * * `emailAddresses[3].type[2]` for a violation in the second `type`
     *   value in the third `emailAddresses` message.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @return The bytes for field.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFieldBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(field_);
    }
    /**
     * <pre>
     * A path that leads to a field in the request body. The value will be a
     * sequence of dot-separated identifiers that identify a protocol buffer
     * field.
     *
     * Consider the following:
     *
     *     message CreateContactRequest {
     *       message EmailAddress {
     *         enum Type {
     *           TYPE_UNSPECIFIED = 0;
     *           HOME = 1;
     *           WORK = 2;
     *         }
     *
     *         optional string email = 1;
     *         repeated EmailType type = 2;
     *       }
     *
     *       string full_name = 1;
     *       repeated EmailAddress email_addresses = 2;
     *     }
     *
     * In this example, in proto `field` could take one of the following values:
     *
     * * `full_name` for a violation in the `full_name` value
     * * `email_addresses[1].email` for a violation in the `email` field of the
     *   first `email_addresses` message
     * * `email_addresses[3].type[2]` for a violation in the second `type`
     *   value in the third `email_addresses` message.
     *
     * In JSON, the same values are represented as:
     *
     * * `fullName` for a violation in the `fullName` value
     * * `emailAddresses[1].email` for a violation in the `email` field of the
     *   first `emailAddresses` message
     * * `emailAddresses[3].type[2]` for a violation in the second `type`
     *   value in the third `emailAddresses` message.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @param value The field to set.
     */
    private void setField(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      field_ = value;
    }
    /**
     * <pre>
     * A path that leads to a field in the request body. The value will be a
     * sequence of dot-separated identifiers that identify a protocol buffer
     * field.
     *
     * Consider the following:
     *
     *     message CreateContactRequest {
     *       message EmailAddress {
     *         enum Type {
     *           TYPE_UNSPECIFIED = 0;
     *           HOME = 1;
     *           WORK = 2;
     *         }
     *
     *         optional string email = 1;
     *         repeated EmailType type = 2;
     *       }
     *
     *       string full_name = 1;
     *       repeated EmailAddress email_addresses = 2;
     *     }
     *
     * In this example, in proto `field` could take one of the following values:
     *
     * * `full_name` for a violation in the `full_name` value
     * * `email_addresses[1].email` for a violation in the `email` field of the
     *   first `email_addresses` message
     * * `email_addresses[3].type[2]` for a violation in the second `type`
     *   value in the third `email_addresses` message.
     *
     * In JSON, the same values are represented as:
     *
     * * `fullName` for a violation in the `fullName` value
     * * `emailAddresses[1].email` for a violation in the `email` field of the
     *   first `emailAddresses` message
     * * `emailAddresses[3].type[2]` for a violation in the second `type`
     *   value in the third `emailAddresses` message.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     */
    private void clearField() {

      field_ = getDefaultInstance().getField();
    }
    /**
     * <pre>
     * A path that leads to a field in the request body. The value will be a
     * sequence of dot-separated identifiers that identify a protocol buffer
     * field.
     *
     * Consider the following:
     *
     *     message CreateContactRequest {
     *       message EmailAddress {
     *         enum Type {
     *           TYPE_UNSPECIFIED = 0;
     *           HOME = 1;
     *           WORK = 2;
     *         }
     *
     *         optional string email = 1;
     *         repeated EmailType type = 2;
     *       }
     *
     *       string full_name = 1;
     *       repeated EmailAddress email_addresses = 2;
     *     }
     *
     * In this example, in proto `field` could take one of the following values:
     *
     * * `full_name` for a violation in the `full_name` value
     * * `email_addresses[1].email` for a violation in the `email` field of the
     *   first `email_addresses` message
     * * `email_addresses[3].type[2]` for a violation in the second `type`
     *   value in the third `email_addresses` message.
     *
     * In JSON, the same values are represented as:
     *
     * * `fullName` for a violation in the `fullName` value
     * * `emailAddresses[1].email` for a violation in the `email` field of the
     *   first `emailAddresses` message
     * * `emailAddresses[3].type[2]` for a violation in the second `type`
     *   value in the third `emailAddresses` message.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @param value The bytes for field to set.
     */
    private void setFieldBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      field_ = value.toStringUtf8();

    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private java.lang.String description_;
    /**
     * <pre>
     * A description of why the request element is bad.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return description_;
    }
    /**
     * <pre>
     * A description of why the request element is bad.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(description_);
    }
    /**
     * <pre>
     * A description of why the request element is bad.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @param value The description to set.
     */
    private void setDescription(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      description_ = value;
    }
    /**
     * <pre>
     * A description of why the request element is bad.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     */
    private void clearDescription() {

      description_ = getDefaultInstance().getDescription();
    }
    /**
     * <pre>
     * A description of why the request element is bad.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     */
    private void setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      description_ = value.toStringUtf8();

    }

    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.viam.shaded.com.google.rpc.BadRequest.FieldViolation prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * A message type used to describe a single bad request field.
     * </pre>
     *
     * Protobuf type {@code google.rpc.BadRequest.FieldViolation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.viam.shaded.com.google.rpc.BadRequest.FieldViolation, Builder> implements
        // @@protoc_insertion_point(builder_implements:google.rpc.BadRequest.FieldViolation)
        com.viam.shaded.com.google.rpc.BadRequest.FieldViolationOrBuilder {
      // Construct using com.google.rpc.BadRequest.FieldViolation.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * A path that leads to a field in the request body. The value will be a
       * sequence of dot-separated identifiers that identify a protocol buffer
       * field.
       *
       * Consider the following:
       *
       *     message CreateContactRequest {
       *       message EmailAddress {
       *         enum Type {
       *           TYPE_UNSPECIFIED = 0;
       *           HOME = 1;
       *           WORK = 2;
       *         }
       *
       *         optional string email = 1;
       *         repeated EmailType type = 2;
       *       }
       *
       *       string full_name = 1;
       *       repeated EmailAddress email_addresses = 2;
       *     }
       *
       * In this example, in proto `field` could take one of the following values:
       *
       * * `full_name` for a violation in the `full_name` value
       * * `email_addresses[1].email` for a violation in the `email` field of the
       *   first `email_addresses` message
       * * `email_addresses[3].type[2]` for a violation in the second `type`
       *   value in the third `email_addresses` message.
       *
       * In JSON, the same values are represented as:
       *
       * * `fullName` for a violation in the `fullName` value
       * * `emailAddresses[1].email` for a violation in the `email` field of the
       *   first `emailAddresses` message
       * * `emailAddresses[3].type[2]` for a violation in the second `type`
       *   value in the third `emailAddresses` message.
       * </pre>
       *
       * <code>string field = 1 [json_name = "field"];</code>
       * @return The field.
       */
      @java.lang.Override
      public java.lang.String getField() {
        return instance.getField();
      }
      /**
       * <pre>
       * A path that leads to a field in the request body. The value will be a
       * sequence of dot-separated identifiers that identify a protocol buffer
       * field.
       *
       * Consider the following:
       *
       *     message CreateContactRequest {
       *       message EmailAddress {
       *         enum Type {
       *           TYPE_UNSPECIFIED = 0;
       *           HOME = 1;
       *           WORK = 2;
       *         }
       *
       *         optional string email = 1;
       *         repeated EmailType type = 2;
       *       }
       *
       *       string full_name = 1;
       *       repeated EmailAddress email_addresses = 2;
       *     }
       *
       * In this example, in proto `field` could take one of the following values:
       *
       * * `full_name` for a violation in the `full_name` value
       * * `email_addresses[1].email` for a violation in the `email` field of the
       *   first `email_addresses` message
       * * `email_addresses[3].type[2]` for a violation in the second `type`
       *   value in the third `email_addresses` message.
       *
       * In JSON, the same values are represented as:
       *
       * * `fullName` for a violation in the `fullName` value
       * * `emailAddresses[1].email` for a violation in the `email` field of the
       *   first `emailAddresses` message
       * * `emailAddresses[3].type[2]` for a violation in the second `type`
       *   value in the third `emailAddresses` message.
       * </pre>
       *
       * <code>string field = 1 [json_name = "field"];</code>
       * @return The bytes for field.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFieldBytes() {
        return instance.getFieldBytes();
      }
      /**
       * <pre>
       * A path that leads to a field in the request body. The value will be a
       * sequence of dot-separated identifiers that identify a protocol buffer
       * field.
       *
       * Consider the following:
       *
       *     message CreateContactRequest {
       *       message EmailAddress {
       *         enum Type {
       *           TYPE_UNSPECIFIED = 0;
       *           HOME = 1;
       *           WORK = 2;
       *         }
       *
       *         optional string email = 1;
       *         repeated EmailType type = 2;
       *       }
       *
       *       string full_name = 1;
       *       repeated EmailAddress email_addresses = 2;
       *     }
       *
       * In this example, in proto `field` could take one of the following values:
       *
       * * `full_name` for a violation in the `full_name` value
       * * `email_addresses[1].email` for a violation in the `email` field of the
       *   first `email_addresses` message
       * * `email_addresses[3].type[2]` for a violation in the second `type`
       *   value in the third `email_addresses` message.
       *
       * In JSON, the same values are represented as:
       *
       * * `fullName` for a violation in the `fullName` value
       * * `emailAddresses[1].email` for a violation in the `email` field of the
       *   first `emailAddresses` message
       * * `emailAddresses[3].type[2]` for a violation in the second `type`
       *   value in the third `emailAddresses` message.
       * </pre>
       *
       * <code>string field = 1 [json_name = "field"];</code>
       * @param value The field to set.
       * @return This builder for chaining.
       */
      public Builder setField(
          java.lang.String value) {
        copyOnWrite();
        instance.setField(value);
        return this;
      }
      /**
       * <pre>
       * A path that leads to a field in the request body. The value will be a
       * sequence of dot-separated identifiers that identify a protocol buffer
       * field.
       *
       * Consider the following:
       *
       *     message CreateContactRequest {
       *       message EmailAddress {
       *         enum Type {
       *           TYPE_UNSPECIFIED = 0;
       *           HOME = 1;
       *           WORK = 2;
       *         }
       *
       *         optional string email = 1;
       *         repeated EmailType type = 2;
       *       }
       *
       *       string full_name = 1;
       *       repeated EmailAddress email_addresses = 2;
       *     }
       *
       * In this example, in proto `field` could take one of the following values:
       *
       * * `full_name` for a violation in the `full_name` value
       * * `email_addresses[1].email` for a violation in the `email` field of the
       *   first `email_addresses` message
       * * `email_addresses[3].type[2]` for a violation in the second `type`
       *   value in the third `email_addresses` message.
       *
       * In JSON, the same values are represented as:
       *
       * * `fullName` for a violation in the `fullName` value
       * * `emailAddresses[1].email` for a violation in the `email` field of the
       *   first `emailAddresses` message
       * * `emailAddresses[3].type[2]` for a violation in the second `type`
       *   value in the third `emailAddresses` message.
       * </pre>
       *
       * <code>string field = 1 [json_name = "field"];</code>
       * @return This builder for chaining.
       */
      public Builder clearField() {
        copyOnWrite();
        instance.clearField();
        return this;
      }
      /**
       * <pre>
       * A path that leads to a field in the request body. The value will be a
       * sequence of dot-separated identifiers that identify a protocol buffer
       * field.
       *
       * Consider the following:
       *
       *     message CreateContactRequest {
       *       message EmailAddress {
       *         enum Type {
       *           TYPE_UNSPECIFIED = 0;
       *           HOME = 1;
       *           WORK = 2;
       *         }
       *
       *         optional string email = 1;
       *         repeated EmailType type = 2;
       *       }
       *
       *       string full_name = 1;
       *       repeated EmailAddress email_addresses = 2;
       *     }
       *
       * In this example, in proto `field` could take one of the following values:
       *
       * * `full_name` for a violation in the `full_name` value
       * * `email_addresses[1].email` for a violation in the `email` field of the
       *   first `email_addresses` message
       * * `email_addresses[3].type[2]` for a violation in the second `type`
       *   value in the third `email_addresses` message.
       *
       * In JSON, the same values are represented as:
       *
       * * `fullName` for a violation in the `fullName` value
       * * `emailAddresses[1].email` for a violation in the `email` field of the
       *   first `emailAddresses` message
       * * `emailAddresses[3].type[2]` for a violation in the second `type`
       *   value in the third `emailAddresses` message.
       * </pre>
       *
       * <code>string field = 1 [json_name = "field"];</code>
       * @param value The bytes for field to set.
       * @return This builder for chaining.
       */
      public Builder setFieldBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFieldBytes(value);
        return this;
      }

      /**
       * <pre>
       * A description of why the request element is bad.
       * </pre>
       *
       * <code>string description = 2 [json_name = "description"];</code>
       * @return The description.
       */
      @java.lang.Override
      public java.lang.String getDescription() {
        return instance.getDescription();
      }
      /**
       * <pre>
       * A description of why the request element is bad.
       * </pre>
       *
       * <code>string description = 2 [json_name = "description"];</code>
       * @return The bytes for description.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        return instance.getDescriptionBytes();
      }
      /**
       * <pre>
       * A description of why the request element is bad.
       * </pre>
       *
       * <code>string description = 2 [json_name = "description"];</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        copyOnWrite();
        instance.setDescription(value);
        return this;
      }
      /**
       * <pre>
       * A description of why the request element is bad.
       * </pre>
       *
       * <code>string description = 2 [json_name = "description"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        copyOnWrite();
        instance.clearDescription();
        return this;
      }
      /**
       * <pre>
       * A description of why the request element is bad.
       * </pre>
       *
       * <code>string description = 2 [json_name = "description"];</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDescriptionBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:google.rpc.BadRequest.FieldViolation)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.viam.shaded.com.google.rpc.BadRequest.FieldViolation();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "field_",
              "description_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.viam.shaded.com.google.rpc.BadRequest.FieldViolation> parser = PARSER;
          if (parser == null) {
            synchronized (com.viam.shaded.com.google.rpc.BadRequest.FieldViolation.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.viam.shaded.com.google.rpc.BadRequest.FieldViolation>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:google.rpc.BadRequest.FieldViolation)
    private static final com.viam.shaded.com.google.rpc.BadRequest.FieldViolation DEFAULT_INSTANCE;
    static {
      FieldViolation defaultInstance = new FieldViolation();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FieldViolation.class, defaultInstance);
    }

    public static com.viam.shaded.com.google.rpc.BadRequest.FieldViolation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FieldViolation> PARSER;

    public static com.google.protobuf.Parser<FieldViolation> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static final int FIELD_VIOLATIONS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.viam.shaded.com.google.rpc.BadRequest.FieldViolation> fieldViolations_;
  /**
   * <pre>
   * Describes all violations in a client request.
   * </pre>
   *
   * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public java.util.List<com.viam.shaded.com.google.rpc.BadRequest.FieldViolation> getFieldViolationsList() {
    return fieldViolations_;
  }
  /**
   * <pre>
   * Describes all violations in a client request.
   * </pre>
   *
   * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  public java.util.List<? extends com.viam.shaded.com.google.rpc.BadRequest.FieldViolationOrBuilder> 
      getFieldViolationsOrBuilderList() {
    return fieldViolations_;
  }
  /**
   * <pre>
   * Describes all violations in a client request.
   * </pre>
   *
   * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public int getFieldViolationsCount() {
    return fieldViolations_.size();
  }
  /**
   * <pre>
   * Describes all violations in a client request.
   * </pre>
   *
   * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public com.viam.shaded.com.google.rpc.BadRequest.FieldViolation getFieldViolations(int index) {
    return fieldViolations_.get(index);
  }
  /**
   * <pre>
   * Describes all violations in a client request.
   * </pre>
   *
   * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  public com.viam.shaded.com.google.rpc.BadRequest.FieldViolationOrBuilder getFieldViolationsOrBuilder(
      int index) {
    return fieldViolations_.get(index);
  }
  private void ensureFieldViolationsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.viam.shaded.com.google.rpc.BadRequest.FieldViolation> tmp = fieldViolations_;
    if (!tmp.isModifiable()) {
      fieldViolations_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * Describes all violations in a client request.
   * </pre>
   *
   * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  private void setFieldViolations(
      int index, com.viam.shaded.com.google.rpc.BadRequest.FieldViolation value) {
    value.getClass();
  ensureFieldViolationsIsMutable();
    fieldViolations_.set(index, value);
  }
  /**
   * <pre>
   * Describes all violations in a client request.
   * </pre>
   *
   * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  private void addFieldViolations(com.viam.shaded.com.google.rpc.BadRequest.FieldViolation value) {
    value.getClass();
  ensureFieldViolationsIsMutable();
    fieldViolations_.add(value);
  }
  /**
   * <pre>
   * Describes all violations in a client request.
   * </pre>
   *
   * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  private void addFieldViolations(
      int index, com.viam.shaded.com.google.rpc.BadRequest.FieldViolation value) {
    value.getClass();
  ensureFieldViolationsIsMutable();
    fieldViolations_.add(index, value);
  }
  /**
   * <pre>
   * Describes all violations in a client request.
   * </pre>
   *
   * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  private void addAllFieldViolations(
      java.lang.Iterable<? extends com.viam.shaded.com.google.rpc.BadRequest.FieldViolation> values) {
    ensureFieldViolationsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, fieldViolations_);
  }
  /**
   * <pre>
   * Describes all violations in a client request.
   * </pre>
   *
   * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  private void clearFieldViolations() {
    fieldViolations_ = emptyProtobufList();
  }
  /**
   * <pre>
   * Describes all violations in a client request.
   * </pre>
   *
   * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  private void removeFieldViolations(int index) {
    ensureFieldViolationsIsMutable();
    fieldViolations_.remove(index);
  }

  public static com.viam.shaded.com.google.rpc.BadRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.viam.shaded.com.google.rpc.BadRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.viam.shaded.com.google.rpc.BadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.viam.shaded.com.google.rpc.BadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.viam.shaded.com.google.rpc.BadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.viam.shaded.com.google.rpc.BadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.viam.shaded.com.google.rpc.BadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.viam.shaded.com.google.rpc.BadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.viam.shaded.com.google.rpc.BadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.viam.shaded.com.google.rpc.BadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.viam.shaded.com.google.rpc.BadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.viam.shaded.com.google.rpc.BadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.viam.shaded.com.google.rpc.BadRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Describes violations in a client request. This error type focuses on the
   * syntactic aspects of the request.
   * </pre>
   *
   * Protobuf type {@code google.rpc.BadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.viam.shaded.com.google.rpc.BadRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.rpc.BadRequest)
      com.viam.shaded.com.google.rpc.BadRequestOrBuilder {
    // Construct using com.google.rpc.BadRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    @java.lang.Override
    public java.util.List<com.viam.shaded.com.google.rpc.BadRequest.FieldViolation> getFieldViolationsList() {
      return java.util.Collections.unmodifiableList(
          instance.getFieldViolationsList());
    }
    /**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    @java.lang.Override
    public int getFieldViolationsCount() {
      return instance.getFieldViolationsCount();
    }/**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    @java.lang.Override
    public com.viam.shaded.com.google.rpc.BadRequest.FieldViolation getFieldViolations(int index) {
      return instance.getFieldViolations(index);
    }
    /**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder setFieldViolations(
        int index, com.viam.shaded.com.google.rpc.BadRequest.FieldViolation value) {
      copyOnWrite();
      instance.setFieldViolations(index, value);
      return this;
    }
    /**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder setFieldViolations(
        int index, com.viam.shaded.com.google.rpc.BadRequest.FieldViolation.Builder builderForValue) {
      copyOnWrite();
      instance.setFieldViolations(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(com.viam.shaded.com.google.rpc.BadRequest.FieldViolation value) {
      copyOnWrite();
      instance.addFieldViolations(value);
      return this;
    }
    /**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(
        int index, com.viam.shaded.com.google.rpc.BadRequest.FieldViolation value) {
      copyOnWrite();
      instance.addFieldViolations(index, value);
      return this;
    }
    /**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(
        com.viam.shaded.com.google.rpc.BadRequest.FieldViolation.Builder builderForValue) {
      copyOnWrite();
      instance.addFieldViolations(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(
        int index, com.viam.shaded.com.google.rpc.BadRequest.FieldViolation.Builder builderForValue) {
      copyOnWrite();
      instance.addFieldViolations(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder addAllFieldViolations(
        java.lang.Iterable<? extends com.viam.shaded.com.google.rpc.BadRequest.FieldViolation> values) {
      copyOnWrite();
      instance.addAllFieldViolations(values);
      return this;
    }
    /**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder clearFieldViolations() {
      copyOnWrite();
      instance.clearFieldViolations();
      return this;
    }
    /**
     * <pre>
     * Describes all violations in a client request.
     * </pre>
     *
     * <code>repeated .google.rpc.BadRequest.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder removeFieldViolations(int index) {
      copyOnWrite();
      instance.removeFieldViolations(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.rpc.BadRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.viam.shaded.com.google.rpc.BadRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "fieldViolations_",
            com.viam.shaded.com.google.rpc.BadRequest.FieldViolation.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.viam.shaded.com.google.rpc.BadRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.viam.shaded.com.google.rpc.BadRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.viam.shaded.com.google.rpc.BadRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.rpc.BadRequest)
  private static final com.viam.shaded.com.google.rpc.BadRequest DEFAULT_INSTANCE;
  static {
    BadRequest defaultInstance = new BadRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      BadRequest.class, defaultInstance);
  }

  public static com.viam.shaded.com.google.rpc.BadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<BadRequest> PARSER;

  public static com.google.protobuf.Parser<BadRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

