// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/rpc/code.proto

// Protobuf Java Version: 3.25.2
package com.viam.shaded.com.google.rpc;

public final class CodeProto {
  private CodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
