// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/reflection/v1alpha/reflection.proto

// Protobuf Java Version: 3.25.2
package com.viam.sdk.core.rpc.reflectionv1alpha;

/**
 * <pre>
 * The error code and error message sent by the server when an error occurs.
 * </pre>
 * <p>
 * Protobuf type {@code grpc.reflection.v1alpha.ErrorResponse}
 */
public final class ErrorResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ErrorResponse, ErrorResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1alpha.ErrorResponse)
    ErrorResponseOrBuilder {

  private ErrorResponse() {
    errorMessage_ = "";
  }

  public static final int ERROR_CODE_FIELD_NUMBER = 1;
  private int errorCode_;

  /**
   * <pre>
   * This field uses the error codes defined in grpc::StatusCode.
   * </pre>
   *
   * <code>int32 error_code = 1 [json_name = "errorCode"];</code>
   *
   * @return The errorCode.
   */
  @Override
  public int getErrorCode() {
    return errorCode_;
  }

  /**
   * <pre>
   * This field uses the error codes defined in grpc::StatusCode.
   * </pre>
   *
   * <code>int32 error_code = 1 [json_name = "errorCode"];</code>
   *
   * @param value The errorCode to set.
   */
  private void setErrorCode(int value) {

    errorCode_ = value;
  }

  /**
   * <pre>
   * This field uses the error codes defined in grpc::StatusCode.
   * </pre>
   *
   * <code>int32 error_code = 1 [json_name = "errorCode"];</code>
   */
  private void clearErrorCode() {

    errorCode_ = 0;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 2;
  private String errorMessage_;

  /**
   * <code>string error_message = 2 [json_name = "errorMessage"];</code>
   *
   * @return The errorMessage.
   */
  @Override
  public String getErrorMessage() {
    return errorMessage_;
  }

  /**
   * <code>string error_message = 2 [json_name = "errorMessage"];</code>
   *
   * @return The bytes for errorMessage.
   */
  @Override
  public com.google.protobuf.ByteString
  getErrorMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(errorMessage_);
  }

  /**
   * <code>string error_message = 2 [json_name = "errorMessage"];</code>
   *
   * @param value The errorMessage to set.
   */
  private void setErrorMessage(
      String value) {
    Class<?> valueClass = value.getClass();

    errorMessage_ = value;
  }

  /**
   * <code>string error_message = 2 [json_name = "errorMessage"];</code>
   */
  private void clearErrorMessage() {

    errorMessage_ = getDefaultInstance().getErrorMessage();
  }

  /**
   * <code>string error_message = 2 [json_name = "errorMessage"];</code>
   *
   * @param value The bytes for errorMessage to set.
   */
  private void setErrorMessageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    errorMessage_ = value.toStringUtf8();

  }

  public static ErrorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ErrorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ErrorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ErrorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ErrorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ErrorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ErrorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }

  public static ErrorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ErrorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static ErrorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ErrorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }

  public static ErrorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(ErrorResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The error code and error message sent by the server when an error occurs.
   * </pre>
   * <p>
   * Protobuf type {@code grpc.reflection.v1alpha.ErrorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
          ErrorResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.reflection.v1alpha.ErrorResponse)
      ErrorResponseOrBuilder {

    // Construct using io.grpc.reflection.v1alpha.ErrorResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * This field uses the error codes defined in grpc::StatusCode.
     * </pre>
     *
     * <code>int32 error_code = 1 [json_name = "errorCode"];</code>
     *
     * @return The errorCode.
     */
    @Override
    public int getErrorCode() {
      return instance.getErrorCode();
    }

    /**
     * <pre>
     * This field uses the error codes defined in grpc::StatusCode.
     * </pre>
     *
     * <code>int32 error_code = 1 [json_name = "errorCode"];</code>
     *
     * @param value The errorCode to set.
     * @return This builder for chaining.
     */
    public Builder setErrorCode(int value) {
      copyOnWrite();
      instance.setErrorCode(value);
      return this;
    }

    /**
     * <pre>
     * This field uses the error codes defined in grpc::StatusCode.
     * </pre>
     *
     * <code>int32 error_code = 1 [json_name = "errorCode"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearErrorCode() {
      copyOnWrite();
      instance.clearErrorCode();
      return this;
    }

    /**
     * <code>string error_message = 2 [json_name = "errorMessage"];</code>
     *
     * @return The errorMessage.
     */
    @Override
    public String getErrorMessage() {
      return instance.getErrorMessage();
    }

    /**
     * <code>string error_message = 2 [json_name = "errorMessage"];</code>
     *
     * @return The bytes for errorMessage.
     */
    @Override
    public com.google.protobuf.ByteString
    getErrorMessageBytes() {
      return instance.getErrorMessageBytes();
    }

    /**
     * <code>string error_message = 2 [json_name = "errorMessage"];</code>
     *
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        String value) {
      copyOnWrite();
      instance.setErrorMessage(value);
      return this;
    }

    /**
     * <code>string error_message = 2 [json_name = "errorMessage"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      copyOnWrite();
      instance.clearErrorMessage();
      return this;
    }

    /**
     * <code>string error_message = 2 [json_name = "errorMessage"];</code>
     *
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setErrorMessageBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grpc.reflection.v1alpha.ErrorResponse)
  }

  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ErrorResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
        Object[] objects = new Object[]{
            "errorCode_",
            "errorMessage_",
        };
        String info =
            "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0208";
        return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ErrorResponse> parser = PARSER;
        if (parser == null) {
          synchronized (ErrorResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ErrorResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grpc.reflection.v1alpha.ErrorResponse)
  private static final ErrorResponse DEFAULT_INSTANCE;

  static {
    ErrorResponse defaultInstance = new ErrorResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ErrorResponse.class, defaultInstance);
  }

  public static ErrorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ErrorResponse> PARSER;

  public static com.google.protobuf.Parser<ErrorResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

