// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/reflection/v1alpha/reflection.proto

// Protobuf Java Version: 3.25.2
package com.viam.sdk.core.rpc.reflectionv1alpha;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.reflection.v1alpha.ErrorResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * This field uses the error codes defined in grpc::StatusCode.
   * </pre>
   *
   * <code>int32 error_code = 1 [json_name = "errorCode"];</code>
   *
   * @return The errorCode.
   */
  int getErrorCode();

  /**
   * <code>string error_message = 2 [json_name = "errorMessage"];</code>
   *
   * @return The errorMessage.
   */
  String getErrorMessage();

  /**
   * <code>string error_message = 2 [json_name = "errorMessage"];</code>
   *
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
  getErrorMessageBytes();
}
