// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/reflection/v1alpha/reflection.proto

// Protobuf Java Version: 3.25.2
package com.viam.sdk.core.rpc.reflectionv1alpha;

public interface ExtensionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.reflection.v1alpha.ExtensionRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Fully-qualified type name. The format should be &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string containing_type = 1 [json_name = "containingType"];</code>
   *
   * @return The containingType.
   */
  String getContainingType();

  /**
   * <pre>
   * Fully-qualified type name. The format should be &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string containing_type = 1 [json_name = "containingType"];</code>
   *
   * @return The bytes for containingType.
   */
  com.google.protobuf.ByteString
  getContainingTypeBytes();

  /**
   * <code>int32 extension_number = 2 [json_name = "extensionNumber"];</code>
   *
   * @return The extensionNumber.
   */
  int getExtensionNumber();
}
