// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/reflection/v1alpha/reflection.proto

// Protobuf Java Version: 3.25.2
package com.viam.sdk.core.rpc.reflectionv1alpha;

/**
 * <pre>
 * A list of extension numbers sent by the server answering
 * all_extension_numbers_of_type request.
 * </pre>
 * <p>
 * Protobuf type {@code grpc.reflection.v1alpha.ExtensionNumberResponse}
 */
public final class ExtensionNumberResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ExtensionNumberResponse, ExtensionNumberResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1alpha.ExtensionNumberResponse)
    ExtensionNumberResponseOrBuilder {

  private ExtensionNumberResponse() {
    baseTypeName_ = "";
    extensionNumber_ = emptyIntList();
  }

  public static final int BASE_TYPE_NAME_FIELD_NUMBER = 1;
  private String baseTypeName_;

  /**
   * <pre>
   * Full name of the base type, including the package name. The format
   * is &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
   *
   * @return The baseTypeName.
   */
  @Override
  public String getBaseTypeName() {
    return baseTypeName_;
  }

  /**
   * <pre>
   * Full name of the base type, including the package name. The format
   * is &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
   *
   * @return The bytes for baseTypeName.
   */
  @Override
  public com.google.protobuf.ByteString
  getBaseTypeNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(baseTypeName_);
  }

  /**
   * <pre>
   * Full name of the base type, including the package name. The format
   * is &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
   *
   * @param value The baseTypeName to set.
   */
  private void setBaseTypeName(
      String value) {
    Class<?> valueClass = value.getClass();

    baseTypeName_ = value;
  }

  /**
   * <pre>
   * Full name of the base type, including the package name. The format
   * is &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
   */
  private void clearBaseTypeName() {

    baseTypeName_ = getDefaultInstance().getBaseTypeName();
  }

  /**
   * <pre>
   * Full name of the base type, including the package name. The format
   * is &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
   *
   * @param value The bytes for baseTypeName to set.
   */
  private void setBaseTypeNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    baseTypeName_ = value.toStringUtf8();

  }

  public static final int EXTENSION_NUMBER_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.IntList extensionNumber_;

  /**
   * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
   *
   * @return A list containing the extensionNumber.
   */
  @Override
  public java.util.List<Integer>
  getExtensionNumberList() {
    return extensionNumber_;
  }

  /**
   * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
   *
   * @return The count of extensionNumber.
   */
  @Override
  public int getExtensionNumberCount() {
    return extensionNumber_.size();
  }

  /**
   * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
   *
   * @param index The index of the element to return.
   * @return The extensionNumber at the given index.
   */
  @Override
  public int getExtensionNumber(int index) {
    return extensionNumber_.getInt(index);
  }

  private int extensionNumberMemoizedSerializedSize = -1;

  private void ensureExtensionNumberIsMutable() {
    com.google.protobuf.Internal.IntList tmp = extensionNumber_;
    if (!tmp.isModifiable()) {
      extensionNumber_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
    }
  }

  /**
   * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
   *
   * @param index The index to set the value at.
   * @param value The extensionNumber to set.
   */
  private void setExtensionNumber(
      int index, int value) {
    ensureExtensionNumberIsMutable();
    extensionNumber_.setInt(index, value);
  }

  /**
   * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
   *
   * @param value The extensionNumber to add.
   */
  private void addExtensionNumber(int value) {
    ensureExtensionNumberIsMutable();
    extensionNumber_.addInt(value);
  }

  /**
   * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
   *
   * @param values The extensionNumber to add.
   */
  private void addAllExtensionNumber(
      Iterable<? extends Integer> values) {
    ensureExtensionNumberIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, extensionNumber_);
  }

  /**
   * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
   */
  private void clearExtensionNumber() {
    extensionNumber_ = emptyIntList();
  }

  public static ExtensionNumberResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ExtensionNumberResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ExtensionNumberResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ExtensionNumberResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ExtensionNumberResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ExtensionNumberResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ExtensionNumberResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }

  public static ExtensionNumberResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ExtensionNumberResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static ExtensionNumberResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ExtensionNumberResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }

  public static ExtensionNumberResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(ExtensionNumberResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A list of extension numbers sent by the server answering
   * all_extension_numbers_of_type request.
   * </pre>
   * <p>
   * Protobuf type {@code grpc.reflection.v1alpha.ExtensionNumberResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
          ExtensionNumberResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.reflection.v1alpha.ExtensionNumberResponse)
      ExtensionNumberResponseOrBuilder {

    // Construct using io.grpc.reflection.v1alpha.ExtensionNumberResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Full name of the base type, including the package name. The format
     * is &lt;package&gt;.&lt;type&gt;
     * </pre>
     *
     * <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
     *
     * @return The baseTypeName.
     */
    @Override
    public String getBaseTypeName() {
      return instance.getBaseTypeName();
    }

    /**
     * <pre>
     * Full name of the base type, including the package name. The format
     * is &lt;package&gt;.&lt;type&gt;
     * </pre>
     *
     * <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
     *
     * @return The bytes for baseTypeName.
     */
    @Override
    public com.google.protobuf.ByteString
    getBaseTypeNameBytes() {
      return instance.getBaseTypeNameBytes();
    }

    /**
     * <pre>
     * Full name of the base type, including the package name. The format
     * is &lt;package&gt;.&lt;type&gt;
     * </pre>
     *
     * <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
     *
     * @param value The baseTypeName to set.
     * @return This builder for chaining.
     */
    public Builder setBaseTypeName(
        String value) {
      copyOnWrite();
      instance.setBaseTypeName(value);
      return this;
    }

    /**
     * <pre>
     * Full name of the base type, including the package name. The format
     * is &lt;package&gt;.&lt;type&gt;
     * </pre>
     *
     * <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearBaseTypeName() {
      copyOnWrite();
      instance.clearBaseTypeName();
      return this;
    }

    /**
     * <pre>
     * Full name of the base type, including the package name. The format
     * is &lt;package&gt;.&lt;type&gt;
     * </pre>
     *
     * <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
     *
     * @param value The bytes for baseTypeName to set.
     * @return This builder for chaining.
     */
    public Builder setBaseTypeNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBaseTypeNameBytes(value);
      return this;
    }

    /**
     * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     *
     * @return A list containing the extensionNumber.
     */
    @Override
    public java.util.List<Integer>
    getExtensionNumberList() {
      return java.util.Collections.unmodifiableList(
          instance.getExtensionNumberList());
    }

    /**
     * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     *
     * @return The count of extensionNumber.
     */
    @Override
    public int getExtensionNumberCount() {
      return instance.getExtensionNumberCount();
    }

    /**
     * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     *
     * @param index The index of the element to return.
     * @return The extensionNumber at the given index.
     */
    @Override
    public int getExtensionNumber(int index) {
      return instance.getExtensionNumber(index);
    }

    /**
     * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     *
     * @param value The extensionNumber to set.
     * @return This builder for chaining.
     */
    public Builder setExtensionNumber(
        int index, int value) {
      copyOnWrite();
      instance.setExtensionNumber(index, value);
      return this;
    }

    /**
     * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     *
     * @param value The extensionNumber to add.
     * @return This builder for chaining.
     */
    public Builder addExtensionNumber(int value) {
      copyOnWrite();
      instance.addExtensionNumber(value);
      return this;
    }

    /**
     * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     *
     * @param values The extensionNumber to add.
     * @return This builder for chaining.
     */
    public Builder addAllExtensionNumber(
        Iterable<? extends Integer> values) {
      copyOnWrite();
      instance.addAllExtensionNumber(values);
      return this;
    }

    /**
     * <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearExtensionNumber() {
      copyOnWrite();
      instance.clearExtensionNumber();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grpc.reflection.v1alpha.ExtensionNumberResponse)
  }

  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ExtensionNumberResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
        Object[] objects = new Object[]{
            "baseTypeName_",
            "extensionNumber_",
        };
        String info =
            "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0208\u0002'";
        return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ExtensionNumberResponse> parser = PARSER;
        if (parser == null) {
          synchronized (ExtensionNumberResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ExtensionNumberResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grpc.reflection.v1alpha.ExtensionNumberResponse)
  private static final ExtensionNumberResponse DEFAULT_INSTANCE;

  static {
    ExtensionNumberResponse defaultInstance = new ExtensionNumberResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ExtensionNumberResponse.class, defaultInstance);
  }

  public static ExtensionNumberResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ExtensionNumberResponse> PARSER;

  public static com.google.protobuf.Parser<ExtensionNumberResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

