// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/reflection/v1alpha/reflection.proto

// Protobuf Java Version: 3.25.2
package com.viam.sdk.core.rpc.reflectionv1alpha;

public interface FileDescriptorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.reflection.v1alpha.FileDescriptorResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
   *
   * @return A list containing the fileDescriptorProto.
   */
  java.util.List<com.google.protobuf.ByteString> getFileDescriptorProtoList();

  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
   *
   * @return The count of fileDescriptorProto.
   */
  int getFileDescriptorProtoCount();

  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
   *
   * @param index The index of the element to return.
   * @return The fileDescriptorProto at the given index.
   */
  com.google.protobuf.ByteString getFileDescriptorProto(int index);
}
