// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/reflection/v1alpha/reflection.proto

// Protobuf Java Version: 3.25.2
package com.viam.sdk.core.rpc.reflectionv1alpha;

/**
 * <pre>
 * Serialized FileDescriptorProto messages sent by the server answering
 * a file_by_filename, file_containing_symbol, or file_containing_extension
 * request.
 * </pre>
 * <p>
 * Protobuf type {@code grpc.reflection.v1alpha.FileDescriptorResponse}
 */
public final class FileDescriptorResponse extends
    com.google.protobuf.GeneratedMessageLite<
        FileDescriptorResponse, FileDescriptorResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1alpha.FileDescriptorResponse)
    FileDescriptorResponseOrBuilder {

  private FileDescriptorResponse() {
    fileDescriptorProto_ = emptyProtobufList();
  }

  public static final int FILE_DESCRIPTOR_PROTO_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> fileDescriptorProto_;

  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
   *
   * @return A list containing the fileDescriptorProto.
   */
  @Override
  public java.util.List<com.google.protobuf.ByteString>
  getFileDescriptorProtoList() {
    return fileDescriptorProto_;
  }

  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
   *
   * @return The count of fileDescriptorProto.
   */
  @Override
  public int getFileDescriptorProtoCount() {
    return fileDescriptorProto_.size();
  }

  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
   *
   * @param index The index of the element to return.
   * @return The fileDescriptorProto at the given index.
   */
  @Override
  public com.google.protobuf.ByteString getFileDescriptorProto(int index) {
    return fileDescriptorProto_.get(index);
  }

  private void ensureFileDescriptorProtoIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> tmp = fileDescriptorProto_;
    if (!tmp.isModifiable()) {
      fileDescriptorProto_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
    }
  }

  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
   *
   * @param index The index to set the value at.
   * @param value The fileDescriptorProto to set.
   */
  private void setFileDescriptorProto(
      int index, com.google.protobuf.ByteString value) {
    Class<?> valueClass = value.getClass();
    ensureFileDescriptorProtoIsMutable();
    fileDescriptorProto_.set(index, value);
  }

  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
   *
   * @param value The fileDescriptorProto to add.
   */
  private void addFileDescriptorProto(com.google.protobuf.ByteString value) {
    Class<?> valueClass = value.getClass();
    ensureFileDescriptorProtoIsMutable();
    fileDescriptorProto_.add(value);
  }

  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
   *
   * @param values The fileDescriptorProto to add.
   */
  private void addAllFileDescriptorProto(
      Iterable<? extends com.google.protobuf.ByteString> values) {
    ensureFileDescriptorProtoIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, fileDescriptorProto_);
  }

  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
   */
  private void clearFileDescriptorProto() {
    fileDescriptorProto_ = emptyProtobufList();
  }

  public static FileDescriptorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static FileDescriptorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static FileDescriptorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static FileDescriptorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static FileDescriptorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static FileDescriptorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static FileDescriptorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }

  public static FileDescriptorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static FileDescriptorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static FileDescriptorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static FileDescriptorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }

  public static FileDescriptorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(FileDescriptorResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Serialized FileDescriptorProto messages sent by the server answering
   * a file_by_filename, file_containing_symbol, or file_containing_extension
   * request.
   * </pre>
   * <p>
   * Protobuf type {@code grpc.reflection.v1alpha.FileDescriptorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
          FileDescriptorResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.reflection.v1alpha.FileDescriptorResponse)
      FileDescriptorResponseOrBuilder {

    // Construct using io.grpc.reflection.v1alpha.FileDescriptorResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
     *
     * @return A list containing the fileDescriptorProto.
     */
    @Override
    public java.util.List<com.google.protobuf.ByteString>
    getFileDescriptorProtoList() {
      return java.util.Collections.unmodifiableList(
          instance.getFileDescriptorProtoList());
    }

    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
     *
     * @return The count of fileDescriptorProto.
     */
    @Override
    public int getFileDescriptorProtoCount() {
      return instance.getFileDescriptorProtoCount();
    }

    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
     *
     * @param index The index of the element to return.
     * @return The fileDescriptorProto at the given index.
     */
    @Override
    public com.google.protobuf.ByteString getFileDescriptorProto(int index) {
      return instance.getFileDescriptorProto(index);
    }

    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
     *
     * @param value The fileDescriptorProto to set.
     * @return This builder for chaining.
     */
    public Builder setFileDescriptorProto(
        int index, com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFileDescriptorProto(index, value);
      return this;
    }

    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
     *
     * @param value The fileDescriptorProto to add.
     * @return This builder for chaining.
     */
    public Builder addFileDescriptorProto(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addFileDescriptorProto(value);
      return this;
    }

    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
     *
     * @param values The fileDescriptorProto to add.
     * @return This builder for chaining.
     */
    public Builder addAllFileDescriptorProto(
        Iterable<? extends com.google.protobuf.ByteString> values) {
      copyOnWrite();
      instance.addAllFileDescriptorProto(values);
      return this;
    }

    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearFileDescriptorProto() {
      copyOnWrite();
      instance.clearFileDescriptorProto();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grpc.reflection.v1alpha.FileDescriptorResponse)
  }

  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new FileDescriptorResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
        Object[] objects = new Object[]{
            "fileDescriptorProto_",
        };
        String info =
            "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001c";
        return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<FileDescriptorResponse> parser = PARSER;
        if (parser == null) {
          synchronized (FileDescriptorResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<FileDescriptorResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grpc.reflection.v1alpha.FileDescriptorResponse)
  private static final FileDescriptorResponse DEFAULT_INSTANCE;

  static {
    FileDescriptorResponse defaultInstance = new FileDescriptorResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FileDescriptorResponse.class, defaultInstance);
  }

  public static FileDescriptorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FileDescriptorResponse> PARSER;

  public static com.google.protobuf.Parser<FileDescriptorResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

