// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/reflection/v1alpha/reflection.proto

// Protobuf Java Version: 3.25.2
package com.viam.sdk.core.rpc.reflectionv1alpha;

/**
 * <pre>
 * The information of a single service used by ListServiceResponse to answer
 * list_services request.
 * </pre>
 * <p>
 * Protobuf type {@code grpc.reflection.v1alpha.ServiceResponse}
 */
public final class ServiceResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ServiceResponse, ServiceResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1alpha.ServiceResponse)
    ServiceResponseOrBuilder {

  private ServiceResponse() {
    name_ = "";
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private String name_;

  /**
   * <pre>
   * Full name of a registered service, including its package name. The format
   * is &lt;package&gt;.&lt;service&gt;
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   *
   * @return The name.
   */
  @Override
  public String getName() {
    return name_;
  }

  /**
   * <pre>
   * Full name of a registered service, including its package name. The format
   * is &lt;package&gt;.&lt;service&gt;
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   *
   * @return The bytes for name.
   */
  @Override
  public com.google.protobuf.ByteString
  getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }

  /**
   * <pre>
   * Full name of a registered service, including its package name. The format
   * is &lt;package&gt;.&lt;service&gt;
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   *
   * @param value The name to set.
   */
  private void setName(
      String value) {
    Class<?> valueClass = value.getClass();

    name_ = value;
  }

  /**
   * <pre>
   * Full name of a registered service, including its package name. The format
   * is &lt;package&gt;.&lt;service&gt;
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }

  /**
   * <pre>
   * Full name of a registered service, including its package name. The format
   * is &lt;package&gt;.&lt;service&gt;
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   *
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static ServiceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ServiceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ServiceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ServiceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ServiceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ServiceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ServiceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }

  public static ServiceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ServiceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static ServiceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }

  public static ServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(ServiceResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The information of a single service used by ListServiceResponse to answer
   * list_services request.
   * </pre>
   * <p>
   * Protobuf type {@code grpc.reflection.v1alpha.ServiceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
          ServiceResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.reflection.v1alpha.ServiceResponse)
      ServiceResponseOrBuilder {

    // Construct using io.grpc.reflection.v1alpha.ServiceResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Full name of a registered service, including its package name. The format
     * is &lt;package&gt;.&lt;service&gt;
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     *
     * @return The name.
     */
    @Override
    public String getName() {
      return instance.getName();
    }

    /**
     * <pre>
     * Full name of a registered service, including its package name. The format
     * is &lt;package&gt;.&lt;service&gt;
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     *
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
    getNameBytes() {
      return instance.getNameBytes();
    }

    /**
     * <pre>
     * Full name of a registered service, including its package name. The format
     * is &lt;package&gt;.&lt;service&gt;
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     *
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }

    /**
     * <pre>
     * Full name of a registered service, including its package name. The format
     * is &lt;package&gt;.&lt;service&gt;
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }

    /**
     * <pre>
     * Full name of a registered service, including its package name. The format
     * is &lt;package&gt;.&lt;service&gt;
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     *
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grpc.reflection.v1alpha.ServiceResponse)
  }

  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ServiceResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
        Object[] objects = new Object[]{
            "name_",
        };
        String info =
            "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
        return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ServiceResponse> parser = PARSER;
        if (parser == null) {
          synchronized (ServiceResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ServiceResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grpc.reflection.v1alpha.ServiceResponse)
  private static final ServiceResponse DEFAULT_INSTANCE;

  static {
    ServiceResponse defaultInstance = new ServiceResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ServiceResponse.class, defaultInstance);
  }

  public static ServiceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ServiceResponse> PARSER;

  public static com.google.protobuf.Parser<ServiceResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

