// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/reflection/v1alpha/reflection.proto

// Protobuf Java Version: 3.25.2
package com.viam.sdk.core.rpc.reflectionv1alpha;

public interface ServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.reflection.v1alpha.ServiceResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Full name of a registered service, including its package name. The format
   * is &lt;package&gt;.&lt;service&gt;
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   *
   * @return The name.
   */
  String getName();

  /**
   * <pre>
   * Full name of a registered service, including its package name. The format
   * is &lt;package&gt;.&lt;service&gt;
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
  getNameBytes();
}
