// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/reflection/v1alpha/reflection.proto

// Protobuf Java Version: 3.25.2
package com.viam.sdk.core.rpc.reflectionv1alpha;

public interface ServerReflectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.reflection.v1alpha.ServerReflectionRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string host = 1 [json_name = "host"];</code>
   *
   * @return The host.
   */
  String getHost();

  /**
   * <code>string host = 1 [json_name = "host"];</code>
   *
   * @return The bytes for host.
   */
  com.google.protobuf.ByteString
  getHostBytes();

  /**
   * <pre>
   * Find a proto file by the file name.
   * </pre>
   *
   * <code>string file_by_filename = 3 [json_name = "fileByFilename"];</code>
   *
   * @return Whether the fileByFilename field is set.
   */
  boolean hasFileByFilename();

  /**
   * <pre>
   * Find a proto file by the file name.
   * </pre>
   *
   * <code>string file_by_filename = 3 [json_name = "fileByFilename"];</code>
   *
   * @return The fileByFilename.
   */
  String getFileByFilename();

  /**
   * <pre>
   * Find a proto file by the file name.
   * </pre>
   *
   * <code>string file_by_filename = 3 [json_name = "fileByFilename"];</code>
   *
   * @return The bytes for fileByFilename.
   */
  com.google.protobuf.ByteString
  getFileByFilenameBytes();

  /**
   * <pre>
   * Find the proto file that declares the given fully-qualified symbol name.
   * This field should be a fully-qualified symbol name
   * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
   * </pre>
   *
   * <code>string file_containing_symbol = 4 [json_name = "fileContainingSymbol"];</code>
   *
   * @return Whether the fileContainingSymbol field is set.
   */
  boolean hasFileContainingSymbol();

  /**
   * <pre>
   * Find the proto file that declares the given fully-qualified symbol name.
   * This field should be a fully-qualified symbol name
   * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
   * </pre>
   *
   * <code>string file_containing_symbol = 4 [json_name = "fileContainingSymbol"];</code>
   *
   * @return The fileContainingSymbol.
   */
  String getFileContainingSymbol();

  /**
   * <pre>
   * Find the proto file that declares the given fully-qualified symbol name.
   * This field should be a fully-qualified symbol name
   * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
   * </pre>
   *
   * <code>string file_containing_symbol = 4 [json_name = "fileContainingSymbol"];</code>
   *
   * @return The bytes for fileContainingSymbol.
   */
  com.google.protobuf.ByteString
  getFileContainingSymbolBytes();

  /**
   * <pre>
   * Find the proto file which defines an extension extending the given
   * message type with the given field number.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5 [json_name =
   * "fileContainingExtension"];</code>
   *
   * @return Whether the fileContainingExtension field is set.
   */
  boolean hasFileContainingExtension();

  /**
   * <pre>
   * Find the proto file which defines an extension extending the given
   * message type with the given field number.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5 [json_name =
   * "fileContainingExtension"];</code>
   *
   * @return The fileContainingExtension.
   */
  ExtensionRequest getFileContainingExtension();

  /**
   * <pre>
   * Finds the tag numbers used by all known extensions of extendee_type, and
   * appends them to ExtensionNumberResponse in an undefined order.
   * Its corresponding method is best-effort: it's not guaranteed that the
   * reflection service will implement this method, and it's not guaranteed
   * that this method will provide all extensions. Returns
   * StatusCode::UNIMPLEMENTED if it's not implemented.
   * This field should be a fully-qualified type name. The format is
   * &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string all_extension_numbers_of_type = 6 [json_name =
   * "allExtensionNumbersOfType"];</code>
   *
   * @return Whether the allExtensionNumbersOfType field is set.
   */
  boolean hasAllExtensionNumbersOfType();

  /**
   * <pre>
   * Finds the tag numbers used by all known extensions of extendee_type, and
   * appends them to ExtensionNumberResponse in an undefined order.
   * Its corresponding method is best-effort: it's not guaranteed that the
   * reflection service will implement this method, and it's not guaranteed
   * that this method will provide all extensions. Returns
   * StatusCode::UNIMPLEMENTED if it's not implemented.
   * This field should be a fully-qualified type name. The format is
   * &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string all_extension_numbers_of_type = 6 [json_name =
   * "allExtensionNumbersOfType"];</code>
   *
   * @return The allExtensionNumbersOfType.
   */
  String getAllExtensionNumbersOfType();

  /**
   * <pre>
   * Finds the tag numbers used by all known extensions of extendee_type, and
   * appends them to ExtensionNumberResponse in an undefined order.
   * Its corresponding method is best-effort: it's not guaranteed that the
   * reflection service will implement this method, and it's not guaranteed
   * that this method will provide all extensions. Returns
   * StatusCode::UNIMPLEMENTED if it's not implemented.
   * This field should be a fully-qualified type name. The format is
   * &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string all_extension_numbers_of_type = 6 [json_name =
   * "allExtensionNumbersOfType"];</code>
   *
   * @return The bytes for allExtensionNumbersOfType.
   */
  com.google.protobuf.ByteString
  getAllExtensionNumbersOfTypeBytes();

  /**
   * <pre>
   * List the full names of registered services. The content will not be
   * checked.
   * </pre>
   *
   * <code>string list_services = 7 [json_name = "listServices"];</code>
   *
   * @return Whether the listServices field is set.
   */
  boolean hasListServices();

  /**
   * <pre>
   * List the full names of registered services. The content will not be
   * checked.
   * </pre>
   *
   * <code>string list_services = 7 [json_name = "listServices"];</code>
   *
   * @return The listServices.
   */
  String getListServices();

  /**
   * <pre>
   * List the full names of registered services. The content will not be
   * checked.
   * </pre>
   *
   * <code>string list_services = 7 [json_name = "listServices"];</code>
   *
   * @return The bytes for listServices.
   */
  com.google.protobuf.ByteString
  getListServicesBytes();

  ServerReflectionRequest.MessageRequestCase getMessageRequestCase();
}
