// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/reflection/v1alpha/reflection.proto

// Protobuf Java Version: 3.25.2
package com.viam.sdk.core.rpc.reflectionv1alpha;

/**
 * <pre>
 * The message sent by the server to answer ServerReflectionInfo method.
 * </pre>
 * <p>
 * Protobuf type {@code grpc.reflection.v1alpha.ServerReflectionResponse}
 */
public final class ServerReflectionResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ServerReflectionResponse, ServerReflectionResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1alpha.ServerReflectionResponse)
    ServerReflectionResponseOrBuilder {

  private ServerReflectionResponse() {
    validHost_ = "";
  }

  private int bitField0_;
  private int messageResponseCase_ = 0;
  private Object messageResponse_;

  public enum MessageResponseCase {
    FILE_DESCRIPTOR_RESPONSE(4),
    ALL_EXTENSION_NUMBERS_RESPONSE(5),
    LIST_SERVICES_RESPONSE(6),
    ERROR_RESPONSE(7),
    MESSAGERESPONSE_NOT_SET(0);
    private final int value;

    MessageResponseCase(int value) {
      this.value = value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MessageResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageResponseCase forNumber(int value) {
      switch (value) {
        case 4:
          return FILE_DESCRIPTOR_RESPONSE;
        case 5:
          return ALL_EXTENSION_NUMBERS_RESPONSE;
        case 6:
          return LIST_SERVICES_RESPONSE;
        case 7:
          return ERROR_RESPONSE;
        case 0:
          return MESSAGERESPONSE_NOT_SET;
        default:
          return null;
      }
    }

    public int getNumber() {
      return this.value;
    }
  }

  @Override
  public MessageResponseCase
  getMessageResponseCase() {
    return MessageResponseCase.forNumber(
        messageResponseCase_);
  }

  private void clearMessageResponse() {
    messageResponseCase_ = 0;
    messageResponse_ = null;
  }

  public static final int VALID_HOST_FIELD_NUMBER = 1;
  private String validHost_;

  /**
   * <code>string valid_host = 1 [json_name = "validHost"];</code>
   *
   * @return The validHost.
   */
  @Override
  public String getValidHost() {
    return validHost_;
  }

  /**
   * <code>string valid_host = 1 [json_name = "validHost"];</code>
   *
   * @return The bytes for validHost.
   */
  @Override
  public com.google.protobuf.ByteString
  getValidHostBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(validHost_);
  }

  /**
   * <code>string valid_host = 1 [json_name = "validHost"];</code>
   *
   * @param value The validHost to set.
   */
  private void setValidHost(
      String value) {
    Class<?> valueClass = value.getClass();

    validHost_ = value;
  }

  /**
   * <code>string valid_host = 1 [json_name = "validHost"];</code>
   */
  private void clearValidHost() {

    validHost_ = getDefaultInstance().getValidHost();
  }

  /**
   * <code>string valid_host = 1 [json_name = "validHost"];</code>
   *
   * @param value The bytes for validHost to set.
   */
  private void setValidHostBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    validHost_ = value.toStringUtf8();

  }

  public static final int ORIGINAL_REQUEST_FIELD_NUMBER = 2;
  private ServerReflectionRequest originalRequest_;

  /**
   * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2 [json_name =
   * "originalRequest"];</code>
   */
  @Override
  public boolean hasOriginalRequest() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2 [json_name =
   * "originalRequest"];</code>
   */
  @Override
  public ServerReflectionRequest getOriginalRequest() {
    return originalRequest_ == null ? ServerReflectionRequest.getDefaultInstance()
        : originalRequest_;
  }

  /**
   * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2 [json_name =
   * "originalRequest"];</code>
   */
  private void setOriginalRequest(ServerReflectionRequest value) {
    value.getClass();
    originalRequest_ = value;
    bitField0_ |= 0x00000001;
  }

  /**
   * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2 [json_name =
   * "originalRequest"];</code>
   */
  @SuppressWarnings({"ReferenceEquality"})
  private void mergeOriginalRequest(ServerReflectionRequest value) {
    value.getClass();
    if (originalRequest_ != null &&
        originalRequest_ != ServerReflectionRequest.getDefaultInstance()) {
      originalRequest_ =
          ServerReflectionRequest.newBuilder(originalRequest_).mergeFrom(value).buildPartial();
    } else {
      originalRequest_ = value;
    }
    bitField0_ |= 0x00000001;
  }

  /**
   * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2 [json_name =
   * "originalRequest"];</code>
   */
  private void clearOriginalRequest() {
    originalRequest_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int FILE_DESCRIPTOR_RESPONSE_FIELD_NUMBER = 4;

  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies. As
   * the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4 [json_name =
   * "fileDescriptorResponse"];</code>
   */
  @Override
  public boolean hasFileDescriptorResponse() {
    return messageResponseCase_ == 4;
  }

  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies. As
   * the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4 [json_name =
   * "fileDescriptorResponse"];</code>
   */
  @Override
  public FileDescriptorResponse getFileDescriptorResponse() {
    if (messageResponseCase_ == 4) {
      return (FileDescriptorResponse) messageResponse_;
    }
    return FileDescriptorResponse.getDefaultInstance();
  }

  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies. As
   * the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4 [json_name =
   * "fileDescriptorResponse"];</code>
   */
  private void setFileDescriptorResponse(FileDescriptorResponse value) {
    value.getClass();
    messageResponse_ = value;
    messageResponseCase_ = 4;
  }

  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies. As
   * the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4 [json_name =
   * "fileDescriptorResponse"];</code>
   */
  private void mergeFileDescriptorResponse(FileDescriptorResponse value) {
    value.getClass();
    if (messageResponseCase_ == 4 &&
        messageResponse_ != FileDescriptorResponse.getDefaultInstance()) {
      messageResponse_ = FileDescriptorResponse.newBuilder(
              (FileDescriptorResponse) messageResponse_)
          .mergeFrom(value).buildPartial();
    } else {
      messageResponse_ = value;
    }
    messageResponseCase_ = 4;
  }

  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies. As
   * the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4 [json_name =
   * "fileDescriptorResponse"];</code>
   */
  private void clearFileDescriptorResponse() {
    if (messageResponseCase_ == 4) {
      messageResponseCase_ = 0;
      messageResponse_ = null;
    }
  }

  public static final int ALL_EXTENSION_NUMBERS_RESPONSE_FIELD_NUMBER = 5;

  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requst.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5
   * [json_name = "allExtensionNumbersResponse"];</code>
   */
  @Override
  public boolean hasAllExtensionNumbersResponse() {
    return messageResponseCase_ == 5;
  }

  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requst.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5
   * [json_name = "allExtensionNumbersResponse"];</code>
   */
  @Override
  public ExtensionNumberResponse getAllExtensionNumbersResponse() {
    if (messageResponseCase_ == 5) {
      return (ExtensionNumberResponse) messageResponse_;
    }
    return ExtensionNumberResponse.getDefaultInstance();
  }

  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requst.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5
   * [json_name = "allExtensionNumbersResponse"];</code>
   */
  private void setAllExtensionNumbersResponse(ExtensionNumberResponse value) {
    value.getClass();
    messageResponse_ = value;
    messageResponseCase_ = 5;
  }

  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requst.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5
   * [json_name = "allExtensionNumbersResponse"];</code>
   */
  private void mergeAllExtensionNumbersResponse(ExtensionNumberResponse value) {
    value.getClass();
    if (messageResponseCase_ == 5 &&
        messageResponse_ != ExtensionNumberResponse.getDefaultInstance()) {
      messageResponse_ = ExtensionNumberResponse.newBuilder(
              (ExtensionNumberResponse) messageResponse_)
          .mergeFrom(value).buildPartial();
    } else {
      messageResponse_ = value;
    }
    messageResponseCase_ = 5;
  }

  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requst.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5
   * [json_name = "allExtensionNumbersResponse"];</code>
   */
  private void clearAllExtensionNumbersResponse() {
    if (messageResponseCase_ == 5) {
      messageResponseCase_ = 0;
      messageResponse_ = null;
    }
  }

  public static final int LIST_SERVICES_RESPONSE_FIELD_NUMBER = 6;

  /**
   * <pre>
   * This message is used to answer list_services request.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6 [json_name =
   * "listServicesResponse"];</code>
   */
  @Override
  public boolean hasListServicesResponse() {
    return messageResponseCase_ == 6;
  }

  /**
   * <pre>
   * This message is used to answer list_services request.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6 [json_name =
   * "listServicesResponse"];</code>
   */
  @Override
  public ListServiceResponse getListServicesResponse() {
    if (messageResponseCase_ == 6) {
      return (ListServiceResponse) messageResponse_;
    }
    return ListServiceResponse.getDefaultInstance();
  }

  /**
   * <pre>
   * This message is used to answer list_services request.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6 [json_name =
   * "listServicesResponse"];</code>
   */
  private void setListServicesResponse(ListServiceResponse value) {
    value.getClass();
    messageResponse_ = value;
    messageResponseCase_ = 6;
  }

  /**
   * <pre>
   * This message is used to answer list_services request.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6 [json_name =
   * "listServicesResponse"];</code>
   */
  private void mergeListServicesResponse(ListServiceResponse value) {
    value.getClass();
    if (messageResponseCase_ == 6 &&
        messageResponse_ != ListServiceResponse.getDefaultInstance()) {
      messageResponse_ = ListServiceResponse.newBuilder((ListServiceResponse) messageResponse_)
          .mergeFrom(value).buildPartial();
    } else {
      messageResponse_ = value;
    }
    messageResponseCase_ = 6;
  }

  /**
   * <pre>
   * This message is used to answer list_services request.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6 [json_name =
   * "listServicesResponse"];</code>
   */
  private void clearListServicesResponse() {
    if (messageResponseCase_ == 6) {
      messageResponseCase_ = 0;
      messageResponse_ = null;
    }
  }

  public static final int ERROR_RESPONSE_FIELD_NUMBER = 7;

  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7 [json_name =
   * "errorResponse"];</code>
   */
  @Override
  public boolean hasErrorResponse() {
    return messageResponseCase_ == 7;
  }

  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7 [json_name =
   * "errorResponse"];</code>
   */
  @Override
  public ErrorResponse getErrorResponse() {
    if (messageResponseCase_ == 7) {
      return (ErrorResponse) messageResponse_;
    }
    return ErrorResponse.getDefaultInstance();
  }

  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7 [json_name =
   * "errorResponse"];</code>
   */
  private void setErrorResponse(ErrorResponse value) {
    value.getClass();
    messageResponse_ = value;
    messageResponseCase_ = 7;
  }

  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7 [json_name =
   * "errorResponse"];</code>
   */
  private void mergeErrorResponse(ErrorResponse value) {
    value.getClass();
    if (messageResponseCase_ == 7 &&
        messageResponse_ != ErrorResponse.getDefaultInstance()) {
      messageResponse_ = ErrorResponse.newBuilder((ErrorResponse) messageResponse_)
          .mergeFrom(value).buildPartial();
    } else {
      messageResponse_ = value;
    }
    messageResponseCase_ = 7;
  }

  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7 [json_name =
   * "errorResponse"];</code>
   */
  private void clearErrorResponse() {
    if (messageResponseCase_ == 7) {
      messageResponseCase_ = 0;
      messageResponse_ = null;
    }
  }

  public static ServerReflectionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ServerReflectionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ServerReflectionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ServerReflectionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ServerReflectionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }

  public static ServerReflectionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ServerReflectionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }

  public static ServerReflectionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ServerReflectionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static ServerReflectionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ServerReflectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }

  public static ServerReflectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(ServerReflectionResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The message sent by the server to answer ServerReflectionInfo method.
   * </pre>
   * <p>
   * Protobuf type {@code grpc.reflection.v1alpha.ServerReflectionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
          ServerReflectionResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.reflection.v1alpha.ServerReflectionResponse)
      ServerReflectionResponseOrBuilder {

    // Construct using io.grpc.reflection.v1alpha.ServerReflectionResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @Override
    public MessageResponseCase
    getMessageResponseCase() {
      return instance.getMessageResponseCase();
    }

    public Builder clearMessageResponse() {
      copyOnWrite();
      instance.clearMessageResponse();
      return this;
    }


    /**
     * <code>string valid_host = 1 [json_name = "validHost"];</code>
     *
     * @return The validHost.
     */
    @Override
    public String getValidHost() {
      return instance.getValidHost();
    }

    /**
     * <code>string valid_host = 1 [json_name = "validHost"];</code>
     *
     * @return The bytes for validHost.
     */
    @Override
    public com.google.protobuf.ByteString
    getValidHostBytes() {
      return instance.getValidHostBytes();
    }

    /**
     * <code>string valid_host = 1 [json_name = "validHost"];</code>
     *
     * @param value The validHost to set.
     * @return This builder for chaining.
     */
    public Builder setValidHost(
        String value) {
      copyOnWrite();
      instance.setValidHost(value);
      return this;
    }

    /**
     * <code>string valid_host = 1 [json_name = "validHost"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearValidHost() {
      copyOnWrite();
      instance.clearValidHost();
      return this;
    }

    /**
     * <code>string valid_host = 1 [json_name = "validHost"];</code>
     *
     * @param value The bytes for validHost to set.
     * @return This builder for chaining.
     */
    public Builder setValidHostBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setValidHostBytes(value);
      return this;
    }

    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2 [json_name =
     * "originalRequest"];</code>
     */
    @Override
    public boolean hasOriginalRequest() {
      return instance.hasOriginalRequest();
    }

    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2 [json_name =
     * "originalRequest"];</code>
     */
    @Override
    public ServerReflectionRequest getOriginalRequest() {
      return instance.getOriginalRequest();
    }

    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2 [json_name =
     * "originalRequest"];</code>
     */
    public Builder setOriginalRequest(ServerReflectionRequest value) {
      copyOnWrite();
      instance.setOriginalRequest(value);
      return this;
    }

    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2 [json_name =
     * "originalRequest"];</code>
     */
    public Builder setOriginalRequest(
        ServerReflectionRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setOriginalRequest(builderForValue.build());
      return this;
    }

    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2 [json_name =
     * "originalRequest"];</code>
     */
    public Builder mergeOriginalRequest(ServerReflectionRequest value) {
      copyOnWrite();
      instance.mergeOriginalRequest(value);
      return this;
    }

    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2 [json_name =
     * "originalRequest"];</code>
     */
    public Builder clearOriginalRequest() {
      copyOnWrite();
      instance.clearOriginalRequest();
      return this;
    }

    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4 [json_name
     * = "fileDescriptorResponse"];</code>
     */
    @Override
    public boolean hasFileDescriptorResponse() {
      return instance.hasFileDescriptorResponse();
    }

    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4 [json_name
     * = "fileDescriptorResponse"];</code>
     */
    @Override
    public FileDescriptorResponse getFileDescriptorResponse() {
      return instance.getFileDescriptorResponse();
    }

    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4 [json_name
     * = "fileDescriptorResponse"];</code>
     */
    public Builder setFileDescriptorResponse(FileDescriptorResponse value) {
      copyOnWrite();
      instance.setFileDescriptorResponse(value);
      return this;
    }

    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4 [json_name
     * = "fileDescriptorResponse"];</code>
     */
    public Builder setFileDescriptorResponse(
        FileDescriptorResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setFileDescriptorResponse(builderForValue.build());
      return this;
    }

    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4 [json_name
     * = "fileDescriptorResponse"];</code>
     */
    public Builder mergeFileDescriptorResponse(FileDescriptorResponse value) {
      copyOnWrite();
      instance.mergeFileDescriptorResponse(value);
      return this;
    }

    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4 [json_name
     * = "fileDescriptorResponse"];</code>
     */
    public Builder clearFileDescriptorResponse() {
      copyOnWrite();
      instance.clearFileDescriptorResponse();
      return this;
    }

    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5
     * [json_name = "allExtensionNumbersResponse"];</code>
     */
    @Override
    public boolean hasAllExtensionNumbersResponse() {
      return instance.hasAllExtensionNumbersResponse();
    }

    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5
     * [json_name = "allExtensionNumbersResponse"];</code>
     */
    @Override
    public ExtensionNumberResponse getAllExtensionNumbersResponse() {
      return instance.getAllExtensionNumbersResponse();
    }

    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5
     * [json_name = "allExtensionNumbersResponse"];</code>
     */
    public Builder setAllExtensionNumbersResponse(ExtensionNumberResponse value) {
      copyOnWrite();
      instance.setAllExtensionNumbersResponse(value);
      return this;
    }

    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5
     * [json_name = "allExtensionNumbersResponse"];</code>
     */
    public Builder setAllExtensionNumbersResponse(
        ExtensionNumberResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setAllExtensionNumbersResponse(builderForValue.build());
      return this;
    }

    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5
     * [json_name = "allExtensionNumbersResponse"];</code>
     */
    public Builder mergeAllExtensionNumbersResponse(ExtensionNumberResponse value) {
      copyOnWrite();
      instance.mergeAllExtensionNumbersResponse(value);
      return this;
    }

    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5
     * [json_name = "allExtensionNumbersResponse"];</code>
     */
    public Builder clearAllExtensionNumbersResponse() {
      copyOnWrite();
      instance.clearAllExtensionNumbersResponse();
      return this;
    }

    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6 [json_name =
     * "listServicesResponse"];</code>
     */
    @Override
    public boolean hasListServicesResponse() {
      return instance.hasListServicesResponse();
    }

    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6 [json_name =
     * "listServicesResponse"];</code>
     */
    @Override
    public ListServiceResponse getListServicesResponse() {
      return instance.getListServicesResponse();
    }

    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6 [json_name =
     * "listServicesResponse"];</code>
     */
    public Builder setListServicesResponse(ListServiceResponse value) {
      copyOnWrite();
      instance.setListServicesResponse(value);
      return this;
    }

    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6 [json_name =
     * "listServicesResponse"];</code>
     */
    public Builder setListServicesResponse(
        ListServiceResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setListServicesResponse(builderForValue.build());
      return this;
    }

    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6 [json_name =
     * "listServicesResponse"];</code>
     */
    public Builder mergeListServicesResponse(ListServiceResponse value) {
      copyOnWrite();
      instance.mergeListServicesResponse(value);
      return this;
    }

    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6 [json_name =
     * "listServicesResponse"];</code>
     */
    public Builder clearListServicesResponse() {
      copyOnWrite();
      instance.clearListServicesResponse();
      return this;
    }

    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7 [json_name =
     * "errorResponse"];</code>
     */
    @Override
    public boolean hasErrorResponse() {
      return instance.hasErrorResponse();
    }

    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7 [json_name =
     * "errorResponse"];</code>
     */
    @Override
    public ErrorResponse getErrorResponse() {
      return instance.getErrorResponse();
    }

    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7 [json_name =
     * "errorResponse"];</code>
     */
    public Builder setErrorResponse(ErrorResponse value) {
      copyOnWrite();
      instance.setErrorResponse(value);
      return this;
    }

    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7 [json_name =
     * "errorResponse"];</code>
     */
    public Builder setErrorResponse(
        ErrorResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setErrorResponse(builderForValue.build());
      return this;
    }

    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7 [json_name =
     * "errorResponse"];</code>
     */
    public Builder mergeErrorResponse(ErrorResponse value) {
      copyOnWrite();
      instance.mergeErrorResponse(value);
      return this;
    }

    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7 [json_name =
     * "errorResponse"];</code>
     */
    public Builder clearErrorResponse() {
      copyOnWrite();
      instance.clearErrorResponse();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grpc.reflection.v1alpha.ServerReflectionResponse)
  }

  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ServerReflectionResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
        Object[] objects = new Object[]{
            "messageResponse_",
            "messageResponseCase_",
            "bitField0_",
            "validHost_",
            "originalRequest_",
            FileDescriptorResponse.class,
            ExtensionNumberResponse.class,
            ListServiceResponse.class,
            ErrorResponse.class,
        };
        String info =
            "\u0000\u0006\u0001\u0001\u0001\u0007\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u1009" +
                "\u0000\u0004<\u0000\u0005<\u0000\u0006<\u0000\u0007<\u0000";
        return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ServerReflectionResponse> parser = PARSER;
        if (parser == null) {
          synchronized (ServerReflectionResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ServerReflectionResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grpc.reflection.v1alpha.ServerReflectionResponse)
  private static final ServerReflectionResponse DEFAULT_INSTANCE;

  static {
    ServerReflectionResponse defaultInstance = new ServerReflectionResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ServerReflectionResponse.class, defaultInstance);
  }

  public static ServerReflectionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ServerReflectionResponse> PARSER;

  public static com.google.protobuf.Parser<ServerReflectionResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

