// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/rpc/context/attribute_context.proto

// Protobuf Java Version: 3.25.2
package com.viam.shaded.com.google.rpc.context;

public final class AttributeContextProto {
  private AttributeContextProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
