name: Generate Documentation

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-docs:
    if: github.repository_owner == 'viamrobotics'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate docs
        run: ./gradlew javadoc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: build/docs/javadoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/javadoc
          publish_branch: docs-gh_pages
          cname: java.viam.dev
