name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  license_finder:
    if: github.repository_owner == 'viamrobotics'
    name: Test
    runs-on: ubuntu-latest
    container:
      # Use Android image because we also run Android tests
      image: cimg/android:2024.01.1

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: ./gradlew test
